name: Build and Push Multi-Arch Docker Images

on:
  release:
    types: [ published ]

jobs:
  package-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update POM version
        run: sed -i "s|<version>0.0.1-SNAPSHOT</version>|<version>${{ github.event.release.tag_name }}</version>|g" pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Copy WAR File
        run: |
          ls -l target/
          cp target/*.war Docker/ROOT.war

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker Images
        working-directory: Docker
        run: |
          # 构建并打上版本标签
          docker buildx build --platform linux/amd64,linux/arm64 --tag mwxmmy/biliupforjava:${{ github.event.release.tag_name }} --push .
          # 构建并打上latest标签
          docker buildx build --platform linux/amd64,linux/arm64 --tag mwxmmy/biliupforjava:latest --push .
      - name: Upload Release Asset
        id: upload-release-asset
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/biliLiveRecord-${{ github.event.release.tag_name }}.war
          asset_name: biliupforjava-${{ github.event.release.tag_name }}.war
          asset_content_type: application/war

  release-assets:
    needs: [ package-and-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: target/*.war # 或者 target/*.jar 等，根据你的项目配置
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}